/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_VDSOCLOCKSOURCE_H
#define __ASM_VDSOCLOCKSOURCE_H

#define VDSO_ARCH_CLOCKMODES	\
	VDSO_CLOCKMODE_ITC,	\
	VDSO_CLOCKMODE_MMIO

#endif /* __ASM_VDSOCLOCKSOURCE_H */
